"""
    Created by Rituraj Ghosh on 21/06/2022
"""
# You are working for the school Principal. We have a database of school students: 
# school = {'Bobby','Tammy','Jammy','Sally','Danny'}
# During class, the teachers take the attendance and compile it into a list
# attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']
# Using what you learned about sets, create a piece of code that the school principal can use to immediately find out who missed the class so they can call the parents. (Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers + the school database to use python and make his/her job easier): Fin the students that miss class!
school = {'Bobby','Tammy','Jammy','Sally','Danny'}
attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']
print(school.difference(attendance_list)) # {'Tammy'}